name: 'Terraform'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-west-1
  TF_VAR_vpc_cdir: ${{ vars.TF_VAR_VPC_CDIR}}
  TF_VAR_project_name: ${{ secrets.TF_VAR_PROJECT_NAME }}
  TF_VAR_subnet_cdir: ${{ vars.TF_VAR_SUBNET_CDIR }}
  TF_VAR_web_server_port: ${{ secrets.TF_VAR_WEB_SERVER_PORT }}
  TF_VAR_database: ${{ secrets.TF_VAR_DATABASE }}
  TF_VAR_db_server_port: ${{ secrets.TF_VAR_DB_SERVER_PORT}}
  TF_VAR_ipaddr: ${{ secrets.TF_VAR_IPADDR }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        environment: [staging]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.TF_MODULE_PRIVATE_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform fmt
      id: fmt
      run: terraform -chdir=./infra fmt -check
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      env:
        AWS_BUCKET_NAME: ${{ secrets.BACKEND_BUCKET_NAME}}
        AWS_BUCKET_KEY: ${{ secrets.BACKEND_KEY}}
      run: terraform -chdir=./infra init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY}" -backend-config="region=${AWS_REGION}"

    - name: Select workspace
      id: workspace
      run: terraform -chdir=./infra workspace select ${{ matrix.environment }}

    - name: Terraform Validate
      id: validate
      run: terraform -chdir=./infra validate -no-color 
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      run: terraform -chdir=./infra plan
      continue-on-error: true
    
    # - uses: actions/github-script@v6
    #   if: github.event_name == 'pull_request'
    #   with:
    #     script: |
    #       const output = `#### Terraform Workspace 📖\`${{ matrix.environment }}\`
    #       #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
    #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
    #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
    #       <details><summary>Validation Output</summary>
    
    #       \`\`\`\n
    #       terraform\n${{ steps.validate.outputs.stdout }}
    #       \`\`\`
    
    #       </details>
    
    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
    #       <details><summary>Show Plan</summary>
    
    #       \`\`\`\n
    #       terraform\n${{ steps.plan.outputs.stdout }}
    #       \`\`\`
    
    #       </details>
    
    #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
    
    #       github.rest.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: output
    #       })

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform -chdir=./infra destroy -auto-approve -input=false